version: "3.8"
services:
  eshop-app:
    image: eshop-app
    container_name: eshop-app
    build: .
    depends_on:
      - eshop-db
    ports:
      - 8000:80
    restart: always
  eshop-db:
    image: eshop-db
    container_name: eshop-db
    build:
      context: .
      dockerfile: Dockerfile.db
    command:
      [
        "--character-set-server=utf8mb4",
        "--collation-server=utf8mb4_unicode_ci",
        "--default-authentication-plugin=mysql_native_password",
      ]
    restart: always
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - 3306:3306
    volumes:
      - "./mysql-data:/var/lib/mysql"
