version: '3.8'

services:
  eshop:
    # image: nefeli/eshop:test
    build: .
    depends_on:
      - db
    ports:
      - 8000:80
  db:
    image: mysql:8.0
    # command: --init-file /docker-entrypoint-initdb.d/1.sql
    # -default-authentication-plugin=mysql_native_password 
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test_db
      MYSQL_USER: devuser
      MYSQL_PASSWORD: devpass
    ports:
      - 6033:3306
    volumes:
      - "./mysql-data:/var/lib/mysql"
      - "./e-shop.sql:/docker-entrypoint-initdb.d/1.sql"