version: '3.8'

services:
  eshop:
    image: eshop:latest
    # build: .
    depends_on:
      - db
    ports:
      - 8000:80
    restart: always
  db:
    image: my-mysql:latest
    command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci','--default-authentication-plugin=mysql_native_password']
    restart: always
    environment:
      MYSQL_DATABASE: test_db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    expose:
      - 3306
    volumes:
      - "./mysql-data:/var/lib/mysql"